name: Python linting

on: [push]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry==1.1.13
        poetry config virtualenvs.create false
        poetry install
    - name: Lint with ruff
      run: |
        ruff app
    - name: Lint with flake8
      run: |
        flake8 app --statistics
    - name: Lint with pylint
      run: |
        pylint app -rn -sn --rcfile=.pylintrc
    - name: Lint with mypy
      run: |
        mypy app --strict --namespace-packages --explicit-package-bases